image: busybox

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  publish: public
  artifacts:
    paths:
      - public
  only:
    - main  # or 'master' depending on your default branch name